### ISSUE TITLE
Not Working after Installation

### ISSUE THREAD

**Issue by larrycflai** [remborg/autoplay#1]
1. After install, it appears on the panel, check labextension, it's ok and enabled.
1. every time clicking either "Set Notebook Autorun config" for the other 2, **nothing happen**
1. While using chrome's inspect feature, it seems that some error due to some js.
1. my nodejs ver. is 10.13. I'm not a developer, n not too familiar with nodejs.
1. JupyterLab ver. 2.2.6

**Comment by remborg** [comment]
Thanks for taking the time to post.
When you click on "Set Notebook Autorun config", I assume you have a notebook open, could you please post the js error message showing in the chrome debugger?

**Comment by remborg** [comment]
I've played around and I've found the issue. 
The bug is fixed, please install the v1.0.1 and give it a try. 

I'm closing this issue, if it still doesn't work please re-open it.
Thanks again for raising the bug :+1:
